name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.LOW_MIST }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit and push files
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "Github Actions" 
          author_email: "actions@github.com"
          message: "Update Profile Summary"
          add: "."
          push: "https://github.com/Shahriar-0/Shahriar-0.git"
